# Generated by Django 2.2.5 on 2019-10-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consignment', '0003_shipment_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shipper_name', models.CharField(max_length=100)),
                ('shipper_address', models.CharField(max_length=100)),
                ('shipper_city', models.CharField(max_length=100)),
                ('shipper_country', models.CharField(max_length=100)),
                ('shipper_tel', models.CharField(max_length=100)),
                ('shipper_email', models.CharField(max_length=100)),
                ('vessel_name', models.CharField(max_length=100)),
                ('voyage_no', models.CharField(max_length=100)),
                ('port_of_loading', models.CharField(max_length=100)),
                ('cfs', models.CharField(max_length=100)),
                ('shipper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consignment.Shipment')),
            ],
        ),
    ]
