# Generated by Django 2.2.5 on 2019-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='measurements',
            new_name='measurement',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='vehicle_details',
            new_name='vehicle_detail',
        ),
        migrations.AlterField(
            model_name='extra',
            name='cfs',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='extra',
            name='destination',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='extra',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
    ]
