# Generated by Django 2.2.5 on 2019-10-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0002_auto_20191011_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
