# Generated by Django 2.2.5 on 2019-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0003_auto_20191011_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='file_ref_no',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
