# Generated by Django 2.2.5 on 2019-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ladding_no', models.CharField(max_length=100)),
                ('shipper', models.CharField(max_length=100)),
                ('consignee1', models.CharField(max_length=100)),
                ('notify_party', models.CharField(max_length=100)),
                ('ocean_vessel', models.CharField(max_length=100)),
                ('voyage_no', models.CharField(max_length=100)),
                ('pol', models.CharField(max_length=100)),
                ('pod', models.CharField(max_length=100)),
                ('final_destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('gross_weight', models.FloatField(max_length=50)),
            ],
        ),
    ]
