# Generated by Django 2.2.5 on 2019-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_auto_20191001_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='measurement',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
